### ISSUE TITLE
Wood laser cutting dimension

### ISSUE THREAD

**Issue by haihaibon** [apollobvm/apollobvm#18]
Could you please adjust drawing dimension? 
![Screenshot_20200405_173556_com autodesk autocadws](https://user-images.githubusercontent.com/63190773/78473472-27bb1700-776b-11ea-9abc-c17313656329.jpg)

**Comment by th3rring** [comment]
Hi there!

Thanks for point this out. We opened the drawings and had no issues with the dimensions. You might have imported them with different units. If you wouldn't mind trying again and seeing if the problem persists. In the meantime, I'm going to close this issue. Feel free to reopen it if you can't find a solution.
