### ISSUE TITLE
error compiling master

### ISSUE THREAD

**Issue by Decstv** [apollobvm/apollobvm#23]
'ventlimits' does not name a type: did you mean ventsettings?

error comes up on the release master.

**Comment by th3rring** [comment]
Which release are you using? We tried adding the ApolloBVM library and compiling the master.ino sketch with the latest release and found no issue. We also tried compiling the sketch on Windows and Linux from the master branch and didn't have any problems.

If you're using the current release and having these problems, you might not have added the ApolloBVM library correctly.

**Comment by Decstv** [comment]
Its version 1.1  
As for the library 'ApolloBVM' it is added and included. Can you remove a library and reinstall?

**Comment by Decstv** [comment]
The issue arised during installing the encoder library install. It would not install with the windows version of arduino. I had to uninstall that ver and inatall elegoo ver.

**Comment by th3rring** [comment]
If you wanted to remove a library, you can locate the arduino directory (this is by default in your Documents directory). There will be a directory called "libraries" which contains all the libraries installed for your Arduino IDE.

For the encoder library, you're going to have to scroll down in the library manager and find the exact library that we specified as a dependency. The one we ended up using is "Encoder by Paul Stoffregen", please use the library manager to install this specific version.

**Comment by Decstv** [comment]
OK will do. 

So I guess the root issue is that the encoder library does not work with the windows store version of the arduino app.

**Comment by Decstv** [comment]
Ps. Thank you

**Comment by th3rring** [comment]
I downloaded the windows store version of the program and still didn't have any issues. I'm not totally sure what the issue you're having is but I would recommend going through the installation instructions carefully again just to make sure. If you run into any issues with it, feedback would definitely be appreciated.

I think there are several other people struggling with this library dependency. I'm going to manually move encoder library into the ApolloBVM library to help prevent this in the future. Thanks!

**Comment by th3rring** [comment]
I've gone ahead and made a new release to integrate the Encoder library into the ApolloBVM library. Please remove the old release and download v1.2.0 from [here](https://github.com/apollobvm/apollobvm/releases/tag/v1.2.0). This should fix any issues with dependencies you were having.
