### ISSUE TITLE
I'm having problems uploading the firmware to the uno

### ISSUE THREAD

**Issue by shusterm-art** [apollobvm/apollobvm#24]
I get the following message:

master 15:1 error encoder

**Comment by th3rring** [comment]
Seems like you might not have installed the encoder library. Unfortunately, Arduino doesn't let us specify library dependencies. Please refer to the following instructions to install the encoder library dependency:

4. Add ApolloBVM library dependencies.
    1. In the Arduino IDE, go to Tools->Manage Libraries...
    2. In the Library Manager, type "Encoder" into the search box.
    3. Scroll down and locate the "Encoder by Paul Stoffregen" library and then click install.

Let me know if you have any other issues with this.

**Comment by th3rring** [comment]
I've gone ahead and made a new release to integrate the Encoder library into the ApolloBVM library. Please remove the old release and download v1.2.0 from the [releases page](https://github.com/apollobvm/apollobvm/releases). Thanks!

**Comment by shusterm-art** [comment]
Now I get this error message:

master:1:10: fatal error:  panel.h: No such file or directory
  #include  "panel.h"
compilation terminated

I can upload example programs fine.

Any suggestions are much appreciated.  Thanks!

**Comment by th3rring** [comment]
Looks like the Arduino IDE is not finding the ApolloBVM library entirely. Did you follow the directions to add the library to the Arduino IDE?

I'll repost the instructions below for clarity.

3. Add the ApolloBVM library to the Arduino IDE:
    1. In the Arduino IDE, go to Sketch->Include Library->Add .ZIP Library...
    2. Navigate to and click on the library zip or library directory inside the extracted release. This will be a file that looks like "ApolloBVM.zip" or a directory with the name "ApolloBVM".

**Comment by shusterm-art** [comment]
I had the encoder installed.  I was able to load the slave controller but not the master.  Thanks again for the help.  The BVM library is installed.  Not sure what else to do.

**Comment by shusterm-art** [comment]
I finally was able to upload the firmware.  Thank you!

**Comment by th3rring** [comment]
Glad to hear it! Going to close this issue now.
