### ISSUE TITLE
What are the pcb components needed for the breadboard?

### ISSUE THREAD

**Issue by shusterm-art** [apollobvm/apollobvm#26]

**Comment by th3rring** [comment]
We've put up a bill of materials and electrical schematic on out [website](http://oedk.rice.edu/apollobvm). You'll have to create an account and sign in to view the materials.

**Comment by shusterm-art** [comment]
Thank you.  I have the BOM for & have everything but couldn't find the specs for the two items added to the breadboard.  Perhaps a diode & cap?

**Comment by th3rring** [comment]
Those should be a 4.7uF capacitor for noise suppression between 5V and ground and a 47k ohm resistor for current limiting on the button.

**Comment by shusterm-art** [comment]
ok.  Thanks.. Are they 100% needed short term testing until I get them?

**Comment by th3rring** [comment]
The 47k ohm resistor is essential, unfortunately. You can use another high value resistor, anything above a couple thousand ohm will be fine.

For the capacitor, we put it on the 5V rail as we noticed a lot of noise from the encoder. You could try without for the time being however if you'd like? I'd still recommend having this there. If you can't source exactly a 4.7uF capacitor, anything around 1 uF - 100 uF or so should be fine.

**Comment by shusterm-art** [comment]
If I can supply 5VDC separately can I eliminate the resistor?

**Comment by th3rring** [comment]
Unfortunately no, the resistor is used to limit the current that's sent through the button and into the Arduino. Again, it doesn't have to be exactly what we specified. We used a 47k ohm resistor as the current drawn when the button is pressed would be 5V/47,000 Ohm = 0.0001 A. You can use anything that pulls a very small amount of current.

**Comment by shusterm-art** [comment]
Thank you for all your help.  I've got the unit up & running.  What is your role on this team?  I sent my info to Mr. Mike Williams about our company Miller Leaman, Inc.  We are building prototypes & have manufacturing capabilities and would like to help.
Marty Shuster
President, Miller Leaman, Inc.
shusterm@millerleaman.com
www.millerleaman.com

**Comment by shusterm-art** [comment]
Thomas,
Thank you for all your help. I've got the unit up & running. What is your role on this team? I sent my info to Mr. Mike Williams about our company Miller Leaman, Inc. We are building prototypes & have manufacturing capabilities and would like to help.
Marty Shuster
President, Miller Leaman, Inc.
shusterm@millerleaman.com<mailto:shusterm@millerleaman.com>
www.millerleaman.com<http://www.millerleaman.com/>
386-562-4121




On Apr 12, 2020, at 5:25 PM, Thomas Herring <notifications@github.com> wrote:

?

Unfortunately no, the resistor is used to limit the current that's sent through the button and into the Arduino. Again, it doesn't have to be exactly what we specified. We used a 47k ohm resistor as the current drawn when the button is pressed would be 5V/47,000 Ohm = 0.0001 A. You can use anything that pulls a very small amount of current.

-

**Comment by th3rring** [comment]
That's amazing! So exciting to see people pick this up and actually build some units. I'm leading the software and electrical engineering efforts on the team here. Mike is one of our media relations specialists and I know he's been quite busy. I'll make sure he gets back to y'all asap however!
