### ISSUE TITLE
LCD Panel backlogged. Shipping estimated 6th August 2020

### ISSUE THREAD

**Issue by Decstv** [apollobvm/apollobvm#29]
The Newhaven NHD-0420D3Z-NSW-BBW-V3  SPI LCD 20x4 panel is unavailable even in small numbers. The Newhaven site has over 400 units on backorder and estimated shipping of August 2020. Is it possible to have an I2C compatible hardware support or adapt the code for the Adafruit SPI backpack ?

**Comment by th3rring** [comment]
Thanks for bringing this up! We are going to look into supporting other 20x4 display models. Technically, it's not a matter of which communication method we use but rather building a different display manager class.

We recommend that you check out [Digikey](https://www.digikey.com/product-detail/en/newhaven-display-intl/NHD-0420D3Z-NSW-BBW-V3/NHD-0420D3Z-NSW-BBW-V3-ND/2626390) as they have plenty of stock.
