### ISSUE TITLE
Archiving the project

### ISSUE THREAD

**Issue by TechnologyClassroom** [apollobvm/apollobvm#32]
I got an email saying, "This project is now being archived.  The ability to login in to get access to the files will be closed on Wednesday, August 4th.  Please download the files, if you wish to continue to get access to them. We will keep the [instructional site](http://oedk.rice.edu/apollobvm) available, if needed."

The mechanical files are currently located on dropbox, but that seems to be going away tomorrow.  It seems the best place for those files would be in this repo or another repo such as <https://github.com/apollobvm/mechanical>.

The [instruction page](http://oedk.rice.edu/apollobvm-diy) behind a login should also be archived along with this maybe as a GitHub page.

**Comment by th3rring** [comment]
Hey there!

Thanks for bringing this to my attention. We actually have also hosted the files on GrabCAD and a link to that can be found [here](https://grabcad.com/library/apollobvm-mk1-rev1-1). I'll also upload the zip file to the repository so it's there. Unfortunately, I'm not planning to work on this project any further but hopefully, there are others that can!

**Comment by TechnologyClassroom** [comment]
It is good to mirror on different sites.  Grabcad requires registration so GitHub would be more accessible.

I was able to download a copy of the website.  If you make a repo for it, I can upload as a PR.  I could do the same for the mechanical repo.
