### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [apollobvm/apollobvm#4]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the AGPLv3 or GPLv3 license so that others are encouraged to contribute changes back to your project.

**Comment by th3rring** [comment]
Yup, good catch. I'll go ahead and make that change. I think I'm going to take your recommendation for GPLv3, just going to run it by admin first. I should be committing it this morning.

**Comment by th3rring** [comment]
Added license, closing this.
